// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InsertTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void insert() {
    driver.get("http://localhost:8080/Bacalaureat/rezultate.jsp");
    driver.manage().window().setSize(new Dimension(1295, 695));
    driver.findElement(By.linkText("Logare")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.name("nume")).click();
    driver.findElement(By.name("nume")).sendKeys("Golat");
    driver.findElement(By.name("init")).sendKeys("R");
    driver.findElement(By.name("prenume")).sendKeys("Mihaela");
    driver.findElement(By.name("cnp")).sendKeys("2546798230345");
    driver.findElement(By.id("liceucombobox")).click();
    {
      WebElement dropdown = driver.findElement(By.id("liceucombobox"));
      dropdown.findElement(By.xpath("//option[. = 'Colegiul National \"C. Negri\"']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("profilcombobox")).click();
    {
      WebElement dropdown = driver.findElement(By.id("profilcombobox"));
      dropdown.findElement(By.xpath("//option[. = 'Stiinte ale Naturii']")).click();
    }
    driver.findElement(By.cssSelector("#profilcombobox > option:nth-child(3)")).click();
    driver.findElement(By.id("submitAdauga")).click();
    driver.findElement(By.cssSelector("#rezultate tr:nth-child(10) > td:nth-child(1)")).click();
    driver.findElement(By.id("initUpdate")).click();
    driver.findElement(By.id("initUpdate")).sendKeys("M");
    driver.findElement(By.id("submitUpdate")).click();
    driver.findElement(By.cssSelector("#rezultate tr:nth-child(10) > td:nth-child(3)")).click();
    driver.findElement(By.id("stergebutton\'9\'")).click();
    js.executeScript("window.scrollTo(0,312)");
  }
}
